server:
  port: 8686

spring:
  application:
    name: admin
  boot:
    admin:
      notify:
        slack:
#          webhook-url: 
#          channel: 

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management.security.enabled: false
 
