spring:
  application:
    name: zuul-proxy

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false

zuul:
  ignoredServices: "*"
  routes:
    sample-app:
      path: /sample-app/**
      service_id: sample-app

