server:
  port: 8081
spring:
  application:
    name: web01
  boot:
    admin:
      url: http://localhost:8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: web02
  application:
    name: web02
server:
  port: 8082
